### ISSUE TITLE
Upgrade to Charm++ v6.8

### ISSUE THREAD

**Issue by jbakosi** [quinoacomputing/quinoa#179]
From: Phil Miller
To: charm@lists.cs.illinois.edu
Subject: Charm++ v6.8.1 Release Candidate

> Hello everyone,
> 
> We have just tagged a release candidate for the next stable release, version 6.8.1, of Charm++. This version has passed all of our automated tests, and has been tested by various Charm++ users already. If there are no major regressions found in it, we will tag the 6.8.1 release next week. You can check out the release in the charm git repo from the git tag 'v6.8.1-rc1'.
> 
> This is a backward compatible patch / bug-fix release of the Charm++ system containing about 100 changes since 6.8.0.
> 
> Please test this code with your applications, and inform us of any identified failures.
> 
> Highlights of those changes are as follows:
> 
> General System Improvements
> 
> - Enable network- and node-topology-aware trees for group and chare array reductions and broadcasts
> - Add a message receive 'fast path' for quicker array element lookup
> - Feature #1434: Optimize degenerate CkLoop cases
> - Fix a rare race condition in Quiescence Detection that could allow it to fire prematurely (bug #1658)
>   * Thanks to Nikhil Jain (LLNL) and Karthik Senthil for isolating this in the Quicksilver proxy application
> - Fix various LB bugs
>   * Fix RefineSwapLB to properly handle non-migratable objects
>   * GreedyRefine: improvements for concurrent=false and HybridLB integration
>   * Bug #1649: NullLB shouldnt wait for LB period
> - Fix Projections tracing bug #1437: CkLoop work traces to the previous entry on the PE rather than to the caller
> - Modify [aggregate] entry method (TRAM) support to only deliver PE-local messages inline for [inline]-annotated methods. This avoids the potential for excessively deep recursion that could overrun thread stacks.
> - Fix various compilation warnings
>
> Platform Support 
> - Improve experimental support for PAMI network layer on POWER8 Linux platforms
>   * Thanks to Sameer Kumar of IBM for contributing these patches
> - Add an experimental 'ofi' network layer to run on Intel Omni-Path hardware using libfabric
>   * Note that support for '+partitions' (also used as '+replicas' by NAMD) is known to be broken, currently (bug #1675)
>   * Thanks to Yohann Burette and Mikhail Shiryaev of Intel for contributing this new network layer
> - The GNI network layer (used on Cray XC/XK/XE systems) now respects the ++quiet command line argument during startup
>
> AMPI Improvements 
> - Support for MPI_IN_PLACE in all collectives and for persistent requests
> - Improved Alltoall(v,w) implementations
> - AMPI now passes all MPICH-3.2 tests for groups, virtual topologies, and infos
> - Fixed Isomalloc to not leave behind mapped memory when migrating off a PE

**Comment by jbakosi** [comment]
Based on private communication with Phil Miller, this now appears necessary to re-enable the BG/Q builds. See https://github.com/quinoacomputing/quinoa/pull/196

**Comment by jbakosi** [comment]
Updating to Charm++ v6.8.2 does fix the Charm++ BG/Q build, but yields further problems:

- `meshconv` fails to link using clang
- numdiff, testu01, trilinos, and charm fail to build using the Intel v18.0.0 compiler, due to https://software.intel.com/en-us/forums/intel-c-compiler/topic/742701. v18.01 should fix this
- the bgclang compiler on BG/Q fails to build:
```
In file included from /bgsys/drivers/V1R2M4/ppc64/gnu-linux-4.7.2/powerpc64-bgq-linux/include/c++/4.7.2/bits/stl_algobase.h:62:
/bgsys/drivers/V1R2M4/ppc64/gnu-linux-4.7.2/powerpc64-bgq-linux/include/c++/4.7.2/bits/cpp_type_traits.h:415:32: error: reference to 'move_iterator' is ambiguous
    struct __is_move_iterator< move_iterator<_Iterator> >
```

**Comment by jbakosi** [comment]
Tried Charm++ v6.8.1, got (only with gcc):
```
Main/meshconv: symbol lookup error: <quinoa-tpl>/install/gnu-x86_64/charm/lib_so/libconv-core.so: undefined symbol: __executable_start
```
even with the fix suggested at https://lists.cs.illinois.edu/lists/arc/charm/2011-08/msg00024.html.

**Comment by jbakosi** [comment]
As described at https://software.intel.com/en-us/forums/intel-c-compiler/topic/742701, the problem with glibc6 goes away with Intel v18.0.1

**Comment by jbakosi** [comment]
Charm++ v6.8.2 and quinoa now build fine on BG/Q.

**Comment by jbakosi** [comment]
The symbol lookup error with gcc is highly likely due to my libc6 - tested on other machines. Does not appear to be a Charm++ update problem. This is done, some BG/Q tests fail, will continue in other issue.
See also https://github.com/quinoacomputing/quinoa-tpl/pull/23.
